Add match section
php-fig/per-coding-style pull request #21
Opened 2022-06-10 15:13 UTC by JesusValera

# 📚 Description

Add the `match` section next to `switch`.

2022-06-16 07:08 UTC, samdark approved these changes

2022-07-17 18:02 UTC, KorvinSzanto requested changes
This should probably be expanded to more specific about more complex match expressions like:
```php
match (true) {
    ...
}
```
See my example from #3: https://3v4l.org/2s8uK

2022-07-23 18:28 UTC, JesusValera commented
I added the following code in the PR:
```php
$returnValue = match ($expr) {
    0 => 'First case',
    1, 2, 3 => multipleCases(),
    default => 'Default case',
};
```

So, `$expr` works for anything (`true` also included).

Which changes do you suggest @KorvinSzanto? 😄

2022-08-09 15:34 UTC, KorvinSzanto approved these changes

2022-08-09 15:35 UTC, merged