Assorted formatting and wording cleanup.
php-fig/per-coding-style pull request #56
Opened 2023-01-13 20:59 UTC by Crell

1. Ensured that every example is preceded with language that makes it clear it is an example (or a bad example, in some cases).
2. Some whitespacing.
3. Collapsed some redundancy.

There should be no substantive changes in this PR.

2023-01-13 21:28 UTC, theodorejb requested changes

2023-01-13 21:28 UTC, theodorejb commented on spec.md
> +MUST be on the component the follow, not on the subsequent line.  For example:
```suggestion
MUST be on the component they follow, not on the subsequent line.  For example:
```

2023-01-14 09:37 UTC, samdark approved these changes

2023-01-14 09:37 UTC, samdark commented on spec.md
> +The following is a correct example of trait `use`age.
```suggestion
The following is a correct example of trait useage.
```

Mixing the code and the word itself looks extremely confusing.

2023-01-17 17:08 UTC, KorvinSzanto requested changes

2023-01-17 17:08 UTC, KorvinSzanto commented on spec.md
> +there are no arguments passed to the constructor.  For example:
Can you update these to all use a single space or a newline before "For example"? I'd prefer sticking with single spaces everywhere.

2023-01-17 17:08 UTC, KorvinSzanto commented on spec.md
> +MUST be on the component they follow, not on the subsequent line.  For example:
> The semicolons MUST be on the component they follow, not on the subsequent line

This is a new requirement, please remove this.

2023-02-05 20:35 UTC, KorvinSzanto approved these changes

2023-02-05 20:35 UTC, merged